### PR TITLE
Document motivation

### PR DESCRIPTION
**Pull request by justinvdm**
Adds a 'motivation' section to the readme.

Thought it'd also be a good time to share this with everyone else on the team, for their context (thus all the reviewers I've added to this PR).

### CODE REVIEW

**Review by ewaldsnaplet — APPROVED** [review]
I love this!

Being able to generate the same data, over and over, is so super handy when you do development.  

Also, having more granular control over what's an very important and, dare I say, critical, feature, just feels better.

Stellar stuff!

**Comment by justinvdm** [comment]
> I love this!
> 
> Being able to generate the same data, over and over, is so super handy when you do development.
> 
> Also, having more granular control over what's an very important and, dare I say, critical, feature, just feels better.
> 
> Stellar stuff!

Thanks for reading and your vote of confidence in the idea @ewaldsnaplet :)

**Review by peterp — APPROVED** [review]
This is fantastic, thanks Justin!

**Comment by justinvdm** [comment]
> This is fantastic, thanks Justin!

Thank you!

**Pull request merged**
